### ISSUE TITLE
Implementasi fungsi hapus kontak

### ISSUE THREAD

**Issue by emhaye** [KodeKreatif/surelia-web-client#108]
- Kontak bisa dihapus dari daftar addressbook

**Comment by herpiko** [comment]
- saat kontak dihapus, simpan ke koleksi kontak_terhapus
- saat kolektor surel berjalan di belakang, ngecek juga ke kontak_terhapus, jika terdaftar, abaikan, jangan dikoleksi
- saat menambahkan kontak secara manual, cek kolek kontak_terhapus, jika terdaftar di sana, hapus dari koleksi tersebut.

**Comment by emhaye** [comment]
Terima kasih pak
