### ISSUE TITLE
Galat jika DB dihapus dan re-deploy

### ISSUE THREAD

**Issue by emhaye** [KodeKreatif/surelia-web-client#109]
Pengujian dengan:
1. reset db
2. deploy
3. login
4. buka ini buka itu
5. biarkan peramban
6. matikan deploy
7. reset db
8. deploy
9. refresh halaman peramban

![screenshot from 2015-11-20 14-02-21](https://cloud.githubusercontent.com/assets/1796162/11293754/86d99ffe-8f8f-11e5-8210-93417c93a51b.png)

**Comment by herpiko** [comment]
Mestinya sudah bisa ditangani sama #71. Mohon dicek.

**Comment by emhaye** [comment]
Terima kasih pak
