### ISSUE TITLE
Kirim pesan ke akunnya sendiri tanpa body

### ISSUE THREAD

**Issue by emhaye** [KodeKreatif/surelia-web-client#146]
- Login sebagai akun `akuntest1`
- Buat pesan baru
- Isi penerima `akuntest1`
- Isi subject
- Body biarkan kosong
- Tekan tombol kirim
- Cek surel masuk, buka pesan yang baru dikirim/masuk, di body `undefined`

**Comment by herpiko** [comment]
https://github.com/KodeKreatif/surelia-web-client/pull/148

**Comment by emhaye** [comment]
Terima kasih pak
