### ISSUE TITLE
Too much `loose` variables

### ISSUE THREAD

**Issue by mdamt** [KodeKreatif/surelia-web-client#27]
The templates contains too much _loose_ variables, which are not tied to the controller, so they live in the `$scope`. The variables should be living in the controller so we can control the easily.

So, in the templates, instead of having `currentMessage`, we should have had `msg.currentMessage`.

**Comment by mdamt** [comment]
Ping @herpiko

**Comment by herpiko** [comment]
Done in https://github.com/KodeKreatif/surelia-web-client/pull/31
