### ISSUE TITLE
Tidak bisa membuka pesan dengan lampiran ukuran > 5 mb

### ISSUE THREAD

**Issue by emhaye** [KodeKreatif/surelia-web-client#75]
Log console:

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```

Log app:

```
Debug: internal, implementation, error
    Error: Timed out while authenticating with server
```

**Comment by herpiko** [comment]
@dotovr @mdamt 

Saya curiga ini karena di backend kelamaan narik data dari imap server. 5M mayan. Jika surelia backend ini berada di suatu tempat yang punya koneksi yang sangat baik dengan imap-nya pnsmail, bakal lancar.

**Comment by herpiko** [comment]
@mdamt Jika batasan timeout request http dari frontend dinaikkan bagaimana pak? Diuji/naikkan sampai bisa narik berkas 30MB tanpa kendala.
