### ISSUE TITLE
Sequence number menjadi tidak konsisten saat satu akun diuji bersamaan oleh dua orang

### ISSUE THREAD

**Issue by herpiko** [KodeKreatif/surelia-web-client#78]
Akun : nabilah. A dan B adalah dua orang penguji berbeda.

Reproduksi : 
- A, buka Trash, ada 4 surel, urutan seq : 1,2,3,4
- B, buka Trash, ada 4 surel, urutan seq : 1,2,3,4
- A, hapus surel kedua, yaitu seq 3, sekarang seq 4 jadi seq 3. seq yang valid : 1,2,3
- B, hapus surel pertama (seq 4 dari sisi B, dapat galat `{ [Error: Error in IMAP command STORE: Invalid messageset] type: 'bad', textCode: undefined, source: 'protocol' }`. Ini terjadi karena seq 4 sudah tidak valid lagi, karena sudah diurutkan ulang jadi seq 3.

**Comment by herpiko** [comment]
Ini nanti ditangani di socket. Setiap ada perubahan jumlah surel di box (hapus/tambah), kirim emit ke client dengan username yang sama, kemudian nilai di angular menyesuaikan.

**Comment by herpiko** [comment]
@mdamt, jadi pakai ws pak? Ini perlu krim ke `room`, bukan broadcast. Tidak ada di ws.
https://github.com/websockets/ws/issues/263
https://github.com/primus/primus#websockets

**Comment by emhaye** [comment]
Terima kasih
