### ISSUE TITLE
Implementasi fungsi menu dropdown yang ada di navigasi

### ISSUE THREAD

**Issue by emhaye** [KodeKreatif/surelia-web-client#85]
![screenshot from 2015-11-13 20-47-51](https://cloud.githubusercontent.com/assets/1796162/11147360/f257e2ba-8a47-11e5-9801-baa3162602a6.png)
![screenshot from 2015-11-13 20-48-03](https://cloud.githubusercontent.com/assets/1796162/11147366/f87fe020-8a47-11e5-9b5b-9467ec668d9a.png)

**Comment by herpiko** [comment]
Ini saya tutup ya pak. Saya pisah menjadi  : 
- sort
- move
